### ISSUE TITLE
TinyTeX requires tinytex::install_tinytex() for full usability

### ISSUE THREAD

**Issue by jenzopr** [conda-forge/r-tinytex-feedstock#5]
Hi all,

the `tinytex` R package requires a call to `tinytex::install_tinytex` to pull in required components and setup the _TinyTex_ latex distribution (see [manual](https://yihui.name/tinytex/)). Otherwise, the package is not fuctional. 
I would be very thankful if someone could comment on how this could be implemented, or where to look for an example. 

Best,
Jens

**Comment by ConorIA** [comment]
Can you not run the command from within R? What is the functionality you are expecting?

```
Rscript -e "tinytex::install_tinytex()"
```
EDIT: Sorry, I misread your comment. I assume you mean they you'd like TinyTeX installed during build. I'm not sure whether the conda forge folks have an opinion one way or another on this. The R package doesn't automatically install TinyTeX, so I'm not sure that the conda package should. 

That said, I think the place to call the command would be in the build/script key in the recipie. I'm not sure whether this key will cause conda-build to ignore the standalone build scripts, which would not be ideal.

**Comment by dbast** [comment]
The description of the package says:

> Summary: Helper functions to install and maintain the 'LaTeX' distribution named 'TinyTeX'

Which means, that the package provides the functionality to install TinyTeX ... it does not contain TinyTex itself.

**Comment by dbast** [comment]
Installing it here via `conda install r-tinytex` followed by `Rscript -e "tinytex::install_tinytex()"` is working here on macOS. Which also looks like to be the intended use according the the description.

**Comment by jdblischak** [comment]
@jenzopr Is there a particular R package on conda-forge that you are having trouble using?

I have lots of thoughts on this :-) I love the TinyTex package. It solves a very tricky problem: how to easily install a minimal LaTeX setup without the use of a package manager like conda/APT/etc/. I've used it multiple times, and it solves this problem very well.

But anyone using this package is also using conda, so I don't think they should actually run `install_tinytex()`. Instead they should run `conda install texlive-core`.

While we could theoretically include this command in the build scripts, this would be a bad idea. TeX Live distributes yearly updates that break existing installations. If TeX Live is installed via conda, it would then break in the next calendar year, and be very hard to debug. See the [TinyTex FAQ](https://yihui.name/tinytex/faq/) on the error `"tlmgr: Remote repository is newer than local (2017 < 2018)"`.

The better conda solution would be to include `texlive-core` as a runtime dependency for any R package that requires LaTeX. If someone wanted to find all the R recipes that list `r-tinytex` as a dependency and add `texlive-core`, that'd be super helpful!

**Comment by jdblischak** [comment]
> If someone wanted to find all the R recipes that list r-tinytex as a dependency and add texlive-core, that'd be super helpful!

Scratch that. The easier solution would be to add `texlive-core` as a runtime dependency to the recipe for `r-tinytex`. Thoughts?

**Comment by ConorIA** [comment]
The reverse imports on CRAN:
bookdown, dlookr, rmarkdown, rticles

That said, I'm not sure that texlive should be a dependency of the TinyTeX package. TinyTeX is required by, bookdown, which is required by blogdown. You don't need LaTeX to publish a blog. In fact, you don't need it for the Gitbook functionality of bookdown. I think users who want LaTeX should install texlive core, but there are use cases where you might not want it (building a Gitbook on GitLab CI is my personal use case).

**Comment by jdblischak** [comment]
> I think users who want LaTeX should install texlive core, but there are use cases where you might not want it (building a Gitbook on GitLab CI is my personal use case).

@ConorIA Agreed. `texlive-core` is a big dependency that isn't always required. Adding it to `r-tinytex` or `r-rmarkdown` would then require it to be installed in all situations.

Perhaps we should leave the situation as is. Users can choose whether to install LaTeX via conda or via TinyTex. @jenzopr Any objections?

**Comment by jenzopr** [comment]
Thanks, John & Conor! 
I'm looking for a lightweight Tex distribution, that I can use in a CI setting to do `R CMD check` on a package I'm maintaining. Unfortunately, `texlive-core` is not enough to check PDFs with `R CMD check`. The issue is known and described [here](https://github.com/conda-forge/texlive-core-feedstock/issues/19). As @dbast suggests, running `Rscript -e "tinytex::install_tinytex()"` works well, but installs TinyTeX in a non-standard location and I would need to symlink everything in place (e.g. `/opt/conda/bin` in the miniconda3 docker container). My idea was to do this work (e.g. moving the installation in place) during the conda build - which hopefully would also server others ☺️ 

Another option would be to create a conda package for TinyTeX itself...
or switch to a different container (`rocker/r`) :wink:

**Comment by jdblischak** [comment]
@jenzopr Wow. I didn't realize that `texlive-core` was non-functional. That is super unfortunate.

> check PDFs with R CMD check

Could you explain more about what you are trying to accomplish? What PDF's are you building? You can use the flag `--no-manual` to skip building of the PDF manual. If you are running `R CMD check` to test your package, I see no benefit in building the manual. Are you using the CI job to build tarballs/binaries for others to install?

> Another option would be to create a conda package for TinyTeX itself...

I think that's a reasonable option. Then the recipe could be updated yearly so that the end user doesn't have to deal with manually updating everything. The main downside would be that any package manually installed with `tlgmr` might be lost.

Lastly I'll note that Travis CI has LaTeX pre-installed for [R package builds](https://docs.travis-ci.com/user/languages/r).

**Comment by jenzopr** [comment]
@jdblischak we're basically trying to mimic the checks that are performed at CRAN upon submission (packages submitted to CRAN are expected to pass `R CMD check --as-cran`, see [source](https://cran.r-project.org/web/packages/submission_checklist.html)). Thanks for pointing out to Travis - I'll have a look!

**Comment by jdblischak** [comment]
> we're basically trying to mimic the checks that are performed at CRAN upon submission (packages submitted to CRAN are expected to pass R CMD check --as-cran, see source).

I agree that is a good idea to test with `--as-cran`, but I don't think building the manual provides much additional information about your package. I set `--no-manual` ([indirectly](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L161) by setting `latex: false` in my .travis.yml file), and I've never had a problem with the manual during submission.

I did a quick test. If there is an error in one of the examples or invalid syntax in an `.Rd` file, `R CMD check --as-cran --no-manual` will send an ERROR or WARNING, respectively.

> Thanks for pointing out to Travis - I'll have a look!

I've been happy with Travis. It is straightforward to test for multiple versions of R for both Linux and macOS. Definitely recommend. I'll also mention [rhub](https://github.com/r-hub/rhub#readme), which has the very useful `rhub::check_for_cran()`.

**Comment by colinbrislawn** [comment]
Any updates on this topic? I'm checking in on conda builds for `osx-arm64`, and I'm not sure if this package is building properly when the install is... uh... unconventional.

The dream is for `mamba install r-tinytex` to work like normal, but I understand if it's more complicated for this package.

> Instead they should run `conda install texlive-core`

Is this still the suggested workaround?

**Comment by jdblischak** [comment]
> The dream is for `mamba install r-tinytex` to work like normal

@colinbrislawn What is your definition of normal? `mamba install r-tinytex` is intended to replicate the behavior of `install.packages("tinytex")`.

> Is this still the suggested workaround?

Yes, please give `conda install texlive-core` a try to see if it works for your use case.

I think what you want is to install the TinyTex distribution itself. That is not what this recipe is for (it's for the R package, that can then be used to install the TinyTex distribution). It's possible to create a recipe to directly install TinyTex, but no one has contributed a recipe yet. We're all volunteers, so if this is something you really need, it'd be great if you could contribute a recipe to share with the conda-forge community.

It looks like the GenomeDK project has created a recipe for TinyTex. You can try out their recipe with `mamba install -c genomedk tinytex`

https://anaconda.org/genomedk/tinytex
https://github.com/GenomeDK/genomedk-docs/blob/d6a429783ad1f0b23afcd16c83e72ec626308d67/docs/software-specific.rst#texlivelatex

**Comment by colinbrislawn** [comment]
Thank you for your help. I'm new to conda-forge and I appreciate your guidance about how I can make this software easy to install for myself and others.

>mamba install r-tinytex is intended to replicate the behavior of install.packages("tinytex").

Good to know!

It sounds like `conda install texlive-core` is what I was looking for. I can only see builds for [linux and osx](https://anaconda.org/conda-forge/texlive-core/files), but not osx-arm64 yet. I'll see if I can get those builds running...
